### PR TITLE
REST API V3: get report list, details & data

### PR DESCRIPTION
**Pull request by ochorocho**
Will add two additional endpoints:

  * /api/2.0/dataset/list - Lists all available reports
  * /api/2.0/dataset/{datasetId}/detail - Lists details about report including metadata, header, dimensions and available series.

### CODE REVIEW

**Comment by Rello** [comment]
Hello @ochorocho 
thank you for this pull.  nice idea

I have a question regarding detail: in fact this is mixing report header data and transactional data.
I have another todo for a pure `getData` 
What do you think about keeping the data out of detail and put this in a second api-call?
would this also work for you? form design point of view its more modular to get the report header once and then the data e.g. on a regular basis

**Comment by ochorocho** [comment]
@Rello ok, reworked the 'detail' endpoint. So there is one endpoint for getting reports details  about header, dimensions and series of a report. On top of that I've added a addtitional enpoint `/apps/analytics/api/2.0/dataset/{datasetId}/data` which also respects filteroptions.

So i can fire 2 requests. 'details' for building a form in my client app, 'data' can then be used to build the chart :-)

**Comment by Rello** [comment]
I will double check. thank you!
may I ask what you are using the API for?

**Comment by ochorocho** [comment]
Working on a NativeScript/vue based android app supposed to manually track data.

**Comment by ochorocho** [comment]
> I will double check. thank you!
> may I ask what you are using the API for?

This is what i got so far https://github.com/ochorocho/nextcloud-analytics-mobile
Can't promise anything.

**Comment by Rello** [comment]
do you have any screenshots or teaser?
I don´t have android. if you get it going, I am more than happy to include the references/advertising in the this app

**Review by Rello — APPROVED** [review]

**Comment by ochorocho** [comment]
Yep, makes sense to me.

**Comment by Rello** [comment]
Hello,
I updated the documentation
https://github.com/Rello/analytics/wiki/API

I did the cleanup and moved your part to the V3 to be consistent.
you would need to adapt your app one more time

        ['name' => 'ApiData#dataAddV3', 'url' => '/api/3.0/data/{datasetId}/add', 'verb' => 'POST'],
        ['name' => 'ApiData#dataDeleteV3', 'url' => '/api/3.0/data/{datasetId}/delete', 'verb' => 'POST'],
        ['name' => 'ApiData#dataGetV3', 'url' => '/api/3.0/data/{datasetId}', 'verb' => 'GET'],
        ['name' => 'ApiData#datasetsIndexV3', 'url' => '/api/3.0/datasets', 'verb' => 'GET'],
        ['name' => 'ApiData#datasetsDetailV3', 'url' => '/api/3.0/datasets/{datasetId}', 'verb' => 'GET'],

let me know if everything works for you

**Comment by Rello** [comment]
@ochorocho 
what is the reason that you use transaction data for the dataset detail?
The report metadata itself (like title, subtitel, dimensiton names, ...) is the correct one here. what was your reason for your implementation?

**Comment by ochorocho** [comment]
Which endpoint are we talking about?

https://github.com/Rello/analytics/wiki/API#datasetsdetail

Gives me the required data including the series. I wanted to build up a form using the JSON data.

```
{
    "header": [
        "Object",
        "Date",
        "Value"
    ],
    "dimensions": {
        "dimension1": "Object",
        "dimension2": "Date"
    },
    "series": [ <-- Used to build a Form for each line/bar on the chart
        "MwH OG",
        "MwH UG"
    ]
}
```

**Comment by ochorocho** [comment]
> let me know if everything works for you

Works as expected. Thank you :-)

**Comment by Rello** [comment]
Hello,
I enhanced it, because the report metadata itself definately needs to be in there (like types, chart/table, filters, ...)

`{
"options":
{"id":365,"name":"New","type":2,"visualization":"ct","chart":"column","parent":0,"dimension1":"Object","dimension2":"Date","subheader":"","chartoptions":"","dataoptions":"","filteroptions":null,"value":"Value","permissions":2},

"header":["Object","Date","Value"],

"dimensions":{"dimension1":"Object","dimension2":"Date"},

"series":["y"]
}
`

**Pull request merged**
